### ISSUE TITLE
Panic because main.rc cannot use unwrap with empty value

### ISSUE THREAD

**Issue by emk2203** [SuspiciousDuck/grav1an#3]
When I try to run `RUST_BACKTRACE=1 grav1an -i /srv/media/input dir/ -o /srv/media/output dir/ -n "Show Name" -w 4
` (all bolded dependencies are installed), I get 

```
thread 'main' panicked at src/main.rs:349:44:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: grav1an::extract_episode_number
   5: grav1an::process_command
   6: grav1an::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Any ideas? System is running Arch.

**Comment by SuspiciousDuck** [comment]
Looks like the regex used to match the episode number is failing, and then grav1an tries to unwrap the regex group but gets None. You can fix this by renaming the input files to match the episode pattern 1 ("XX") or 2 ("SXXEXX") where X = episode or season number. You could also just add the argument --not-show and --inherit-name so it skips show-specific code and makes the output have the same name as the input.

**Comment by emk2203** [comment]
OK, I fixed the issue by renaming according to pattern 2.

But then, another unwrap issue pops up after I started with the same command line as above.

```
RUST_BACKTRACE=1 grav1an -i /srv/media/\[hayden\]\ Himitsu\ No\ Akko-Chan\ \(1969\)/ -o /srv/media/output/ -n "Himitsu no Akko-chan" -w 4
Input directory: "/srv/media/[hayden] Himitsu No Akko-Chan (1969)/"
/srv/media/[hayden] Himitsu No Akko-Chan (1969)/[hayden] Himitsu no Akko-chan - S01E02.mkv
Episode 02
Output path: /srv/media/output/[Group] Himitsu no Akko-chan - 02 [1080p.AV1].mkv
Collecting video information for /srv/media/[hayden] Himitsu No Akko-Chan (1969)/[hayden] Himitsu no Akko-chan - S01E02.mkv
Encoding using libopus 1.5.2 (audio)
-----------------------------------------------------
   Input: 48 kHz, 2 channels
  Output: 2 channels (2 coupled)
          20ms packets, 128 kbit/s VBR
 Preskip: 312

Encoding complete                            
-----------------------------------------------------
       Encoded: 25 minutes and 6.12 seconds
       Runtime: 10 seconds
                (150.6x realtime)
         Wrote: 19546856 bytes, 75306 packets, 1509 pages
       Bitrate: 103.039 kbit/s (without overhead)
 Instant rates: 55.2 to 258 kbit/s
                (138 to 645 bytes per packet)
      Overhead: 0.758% (container+metadata)


thread 'main' panicked at src/main.rs:249:104:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: grav1an::Probe::color_data
   5: grav1an::process_command
   6: grav1an::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Is there a convention how to name the files/dirs? Currently, I have `[aaa] Title with spaces - S01E01.mkv`.

**Comment by SuspiciousDuck** [comment]
Can I see what the output of `ffprobe -v error -show_streams -select_streams v '/srv/media/[hayden] Himitsu No Akko-Chan (1969)/[hayden] Himitsu no Akko-chan - S01E02.mkv'` is?

**Comment by emk2203** [comment]
Sure, it's

```
$ ffprobe -v error -show_streams -select_streams v '/srv/media/[hayden] Himitsu No Akko-Chan (1969)/[hayden] Himitsu no Akko-chan - S01E02.mkv'
[STREAM]
index=0
codec_name=mpeg2video
codec_long_name=MPEG-2 video
profile=Main
codec_type=video
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
width=720
height=480
coded_width=0
coded_height=0
closed_captions=0
film_grain=0
has_b_frames=1
sample_aspect_ratio=8:9
display_aspect_ratio=4:3
pix_fmt=yuv420p
level=8
color_range=tv
color_space=smpte170m
color_transfer=smpte170m
color_primaries=smpte170m
chroma_location=left
field_order=tt
refs=1
id=N/A
r_frame_rate=30000/1001
avg_frame_rate=30000/1001
time_base=1/1000
start_pts=0
start_time=0.000000
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
extradata_size=164
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
DISPOSITION:multilayer=0
TAG:language=eng
TAG:BPS=6812027
TAG:DURATION=00:25:06.605000000
TAG:NUMBER_OF_FRAMES=36134
TAG:NUMBER_OF_BYTES=1282879388
TAG:SOURCE_ID=0100E0
TAG:_STATISTICS_WRITING_APP=mkvmerge v89.0 ('And the Melody Still Lingers On (Night in Tunisia)') 64-bit
TAG:_STATISTICS_WRITING_DATE_UTC=2025-07-22 23:03:26
TAG:_STATISTICS_TAGS=BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
[SIDE_DATA]
side_data_type=CPB properties
max_bitrate=9800000
min_bitrate=0
avg_bitrate=0
buffer_size=1835008
vbv_delay=-1
[/SIDE_DATA]
[/STREAM]
```

There is already a `'[hayden] Himitsu no Akko-chan - S01E02.mkv.ffprobe` file in the dir with this information in json format, also a `'[hayden] Himitsu no Akko-chan - S01E02.1.jpn.opus` file. Maybe this info helps assess where the issue happens.

**Comment by SuspiciousDuck** [comment]
I pushed a commit that handles smpte170m color information. Try now.

**Comment by emk2203** [comment]
Thanks, this gets me past the scene detection.

Unfortunately, there's still an issue remaining:

```
Params: --crf 55 --preset 8 --tune 3 --sharpness 2 --variance-boost-strength 4 --variance-octile 4 --frame-luma-bias 100 --keyint 0 --enable-dlf 2 --enable-cdef 0 --enable-restoration 0 --enable-tf 0 --color-range 0 --matrix-coefficients 6 --transfer-characteristics 6 --color-primaries 6
  [Chunk  48] 
  [Chunk  79] 
  [Chunk 170] 
  [Chunk  25] 
⠒ 00:00:00 ▕                                                                                                                                    ▏   0%  0/3614 (0 fps, eta unknown)2025-07-29T16:16:58.283770Z ERROR av1an_core::broker: [chunk 79] encoder failed 3 times, shutting down worker
2025-07-29T16:16:58.283943Z ERROR av1an_core::broker: [chunk 79] encoder crashed: exit status: 1
stdout:

stderr:
        Svt[info]: -------------------------------------------
        Svt[info]: SVT [version]:       SVT-AV1 Encoder Lib v3.0.2-dirty
        Svt[info]: SVT [build]  :       GCC 14.2.1 20250207      64 bit
        Svt[info]: LIB Build date: Mar 26 2025 14:07:49
        Svt[info]: -------------------------------------------
        Error: Invalid parameter 'enable-dlf' with value '2'
        Unprocessed tokens: --frame-luma-bias 

        Unprocessed arguments: 100 

        Error in configuration, could not begin encoding! ... 
        Run SvtAv1EncApp --help for a list of options
        SvtMalloc[info]: you have no memory leak


source pipe stderr:

ffmpeg pipe stderr:


thread 'main' panicked at src/main.rs:985:9:
Av1an failed to encode file!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I see that the issue is an invalid parameter `enable-dlf`, but I am not sure where to fix it.

I can encode with `av1an` itself, the following script works well:

```
#!/bin/bash
for file in *.mkv
do
av1an -i "$file" \
-v " \
--deltaq-mode=0 \
--sharpness=1 --profile=0 --end-usage=q --cq-level=15 \
--threads=2 --tile-columns=2 --tile-rows=1 --cpu-used=4 --row-mt=0 \
--enable-fwd-kf=1 --aq-mode=1 --lag-in-frames=48 --bit-depth=10 \
--kf-max-dist=240 --kf-min-dist=12 --enable-qm=1 --sb-size=64 \
--arnr-strength=0 --arnr-maxframes=3 --enable-dnl-denoising=0 \
--denoise-noise-level=5 --enable-restoration=0 --enable-cdef=0 \
--gf-max-pyr-height=4 --max-reference-frames=4 \
" \
-w 10 \
-p 2 -l .log --pix-format yuv420p10le \
-a " -c:a copy " \
-o "/srv/media/output/${file%.*}.mkv"
done
```

The `av1an` version is av1an 0.4.4-unstable (rev VERGEN_IDEMPOTENT_OUTPUT) (Release).

**Comment by SuspiciousDuck** [comment]
Here's where I should mention this project has not been worked on in like 10 months, and that the script it was based on has since gone through many updates. The default parameter list is probably out of date (in svt-av1, the option --frame-luma-bias has since been renamed to --luminance-qp-bias iirc), but I don't feel motivated to work on updating grav1an. However, there is the option --parameters you can set, which allows you to override the default parameters grav1an chooses, so you can feel free to set that.
PS: the bash script you're using to encode uses aomenc, which grav1an doesn't support.

**Comment by emk2203** [comment]
I expected as much, too bad since your implementation has potential. Thanks for pointing out the `--parameters` option, I give it a try. 

Closing the issue since the original issue was solved anyway.
